CREATE TABLE miniproject.smarthomesensor (
  Id INT NOT NULL AUTO_INCREMENT,
  Home_Id VARCHAR(20) NOT NULL,
  Room_Name VARCHAR(20) NOT NULL,
  Sensing_DateTime DATETIME NOT NULL,
  Temp FLOAT NOT NULL,
  Humid FLOAT NOT NULL);
